-- 1. Add validation columns to survey_responses
ALTER TABLE public.survey_responses
  ADD COLUMN IF NOT EXISTS token_validated boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS token_validated_at timestamptz;

-- 2. Function: register a tracking code as a valid token (called when site generates code)
CREATE OR REPLACE FUNCTION public.register_tracking_code(_code text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_normalized text;
BEGIN
  IF _code IS NULL THEN RETURN false; END IF;
  v_normalized := upper(trim(_code));

  IF v_normalized !~ '^UFTC-[A-Z0-9]{4,16}$' THEN
    RETURN false;
  END IF;

  INSERT INTO public.valid_tokens (code, is_active, notes)
  VALUES (v_normalized, true, 'auto-generated by site')
  ON CONFLICT (code) DO NOTHING;

  RETURN true;
END;
$$;

-- Ensure unique constraint on code so ON CONFLICT works
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'valid_tokens_code_key'
  ) THEN
    ALTER TABLE public.valid_tokens ADD CONSTRAINT valid_tokens_code_key UNIQUE (code);
  END IF;
END $$;

-- 3. Function: confirm a survey response with a valid token (called by sync edge function)
CREATE OR REPLACE FUNCTION public.confirm_response_with_token(_tracking_code text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_normalized text;
  v_response_id uuid;
  v_token_ok boolean;
BEGIN
  IF _tracking_code IS NULL THEN RETURN false; END IF;
  v_normalized := upper(trim(_tracking_code));

  IF v_normalized !~ '^UFTC-[A-Z0-9]{4,16}$' THEN
    RETURN false;
  END IF;

  -- Find matching survey_response
  SELECT id INTO v_response_id
  FROM public.survey_responses
  WHERE tracking_code = v_normalized
  LIMIT 1;

  IF v_response_id IS NULL THEN
    RETURN false;
  END IF;

  -- Consume token
  v_token_ok := public.validate_and_consume_token(v_normalized, v_response_id);

  IF NOT v_token_ok THEN
    RETURN false;
  END IF;

  UPDATE public.survey_responses
  SET token_validated = true,
      token_validated_at = now(),
      google_form_completed = true,
      google_form_completed_at = COALESCE(google_form_completed_at, now())
  WHERE id = v_response_id;

  RETURN true;
END;
$$;

-- 4. New table for invalid form attempts
CREATE TABLE IF NOT EXISTS public.invalid_form_responses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  attempted_code text,
  form_submitted_at timestamptz,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  reason text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.invalid_form_responses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can view invalid responses" ON public.invalid_form_responses;
CREATE POLICY "Admins can view invalid responses"
ON public.invalid_form_responses FOR SELECT
TO authenticated
USING (public.has_role(auth.uid(), 'admin'::app_role));

DROP POLICY IF EXISTS "Admins can manage invalid responses insert" ON public.invalid_form_responses;
CREATE POLICY "Admins can manage invalid responses insert"
ON public.invalid_form_responses FOR INSERT
TO authenticated
WITH CHECK (public.has_role(auth.uid(), 'admin'::app_role));

DROP POLICY IF EXISTS "Admins can manage invalid responses update" ON public.invalid_form_responses;
CREATE POLICY "Admins can manage invalid responses update"
ON public.invalid_form_responses FOR UPDATE
TO authenticated
USING (public.has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (public.has_role(auth.uid(), 'admin'::app_role));

DROP POLICY IF EXISTS "Admins can manage invalid responses delete" ON public.invalid_form_responses;
CREATE POLICY "Admins can manage invalid responses delete"
ON public.invalid_form_responses FOR DELETE
TO authenticated
USING (public.has_role(auth.uid(), 'admin'::app_role));

-- Block anon writes
DROP POLICY IF EXISTS "Block anon invalid_form_responses" ON public.invalid_form_responses;
CREATE POLICY "Block anon invalid_form_responses"
ON public.invalid_form_responses AS RESTRICTIVE
FOR ALL
TO anon
USING (false)
WITH CHECK (false);
